spring.application.name=cloth-erp-api
server.port=8080

# Database configuration
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=cloth_erp_db;encrypt=true;trustServerCertificate=true;integratedSecurity=false;
spring.datasource.name=cloth_erp_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

springdoc.packagesToScan=com.misstilo.cloth_erp_api