spring.application.name=cloth-erp-api
server.port=8080

# Database configuration
spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=cloth_erp_db;encrypt=true;trustServerCertificate=true;integratedSecurity=false;
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=sa
spring.datasource.password=Nj&m091515
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver